// Token compiler: W3C/DTCG Figma exports (tokens/*.json) → CSS custom properties.
//
// The Figma exports are a bespoke DTCG dialect:
//   - color $value is an object { colorSpace, components:[r,g,b] (0..1), alpha, hex }
//   - each product file is self-contained: it embeds its own `references`/`alpha`
//     primitive blocks, and semantic tokens alias into them via "{references.gray.900}".
//
// Output (all git-ignored, never hand-edited):
//   src/styles/reference.css      :root  --ref-shades-*, --ref-alphas-*
//   src/styles/measurement.css    :root  --radius-*, --space-*, --size-*,
//                                        --border-width-*, --focus-ring-*, --duration-*
//   src/styles/typography.css     :root  --font-family, --font-size-*, --line-height-*, ...
//   src/styles/themes/<p>.css     [data-theme="<p>"]  --color-<group>-*
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const TOK = join(repoRoot, "tokens");
const OUT = join(repoRoot, "src", "styles");
mkdirSync(join(OUT, "themes"), { recursive: true });

const read = (f) => JSON.parse(readFileSync(join(TOK, f), "utf8"));
const isToken = (n) => n && typeof n === "object" && "$value" in n;
const kebab = (s) =>
  String(s).replace(/([a-z0-9])([A-Z])/g, "$1-$2").replace(/[\s_/.]+/g, "-").toLowerCase();

// Flatten a token tree into { "a.b.c": node } keyed by dot-path (for alias lookup).
function flatten(obj, prefix = "", out = {}) {
  for (const [k, v] of Object.entries(obj)) {
    if (k.startsWith("$")) continue;
    const path = prefix ? `${prefix}.${k}` : k;
    if (isToken(v)) out[path] = v;
    else if (v && typeof v === "object") flatten(v, path, out);
  }
  return out;
}

// Resolve a color $value (object, or "{alias}" string) to a CSS color, following
// alias chains within `flat`. Returns null if it can't be resolved.
function resolveColor(value, flat, seen = new Set()) {
  if (typeof value === "string") {
    const m = value.match(/^\{(.+)\}$/);
    if (!m) return value;
    const path = m[1];
    if (seen.has(path)) return null;
    seen.add(path);
    const target = flat[path];
    return target ? resolveColor(target.$value, flat, seen) : null;
  }
  if (value && typeof value === "object") {
    const a = value.alpha ?? 1;
    if (a >= 1) return String(value.hex).toUpperCase();
    const [r, g, b] = (value.components || []).map((c) => Math.round(c * 255));
    const alpha = Number(a.toFixed(3));
    return `rgba(${r}, ${g}, ${b}, ${alpha})`;
  }
  return null;
}

const banner = "/* GENERATED by scripts/build-tokens.mjs — do not edit. */\n";
const block = (selector, lines) =>
  `${selector} {\n${lines.map((l) => `  ${l}`).join("\n")}\n}\n`;
const write = (rel, css) => {
  const dest = join(OUT, rel);
  writeFileSync(dest, banner + css);
  console.log(`[tokens] ${rel}  (${css.split("\n").length - 1} lines)`);
};

let warnings = 0;
const warn = (m) => {
  warnings++;
  console.warn(`[tokens] WARN ${m}`);
};

// ── 1. References color → reference.css ───────────────────────────────────────
{
  const flat = flatten(read("1. References Color.json"));
  const lines = [];
  for (const [path, node] of Object.entries(flat)) {
    if (node.$type !== "color") continue;
    const css = resolveColor(node.$value, flat);
    if (css == null) { warn(`reference color unresolved: ${path}`); continue; }
    lines.push(`--ref-${kebab(path)}: ${css};`);
  }
  write("reference.css", block(":root", lines));
}

// ── 2. Measurement → measurement.css ──────────────────────────────────────────
{
  const m = read("4. Measurement.json");
  const lines = [];
  // [Figma group, css var prefix, unit]
  const groups = [
    ["Radius", "radius", "px"],
    ["Spacing", "space", "px"],
    ["Size", "size", "px"],
    ["Border Width", "border-width", "px"],
    ["Focus Ring", "focus-ring", "px"],
    ["Duration", "duration", "ms"],
  ];
  for (const [group, varName, unit] of groups) {
    if (!m[group]) continue;
    const flat = flatten(m[group]);
    for (const [path, node] of Object.entries(flat)) {
      lines.push(`--${varName}-${kebab(path)}: ${node.$value}${unit};`);
    }
  }
  write("measurement.css", block(":root", lines));
}

// ── 3. Typography → typography.css ────────────────────────────────────────────
{
  const t = read("3. Typography.json");
  const flat = flatten(t);
  const lines = [];
  const pxGroups = new Set(["size", "line-height", "letter-spacing"]);
  for (const [path, node] of Object.entries(flat)) {
    if (path === "FontName") {
      lines.push(`--font-family: "${node.$value}", "Yekan Bakh FaNum", system-ui, sans-serif;`);
      continue;
    }
    const [head] = path.split(".");
    const g = kebab(head);
    if (g === "size") lines.push(`--font-size-${kebab(path.split(".").slice(1).join("."))}: ${node.$value}px;`);
    else if (g === "line-height") lines.push(`--line-height-${kebab(path.split(".").slice(1).join("."))}: ${node.$value}px;`);
    else if (g === "weight") lines.push(`--font-weight-${kebab(path.split(".").slice(1).join("."))}: ${node.$value};`);
    else if (g === "letter-spacing") lines.push(`--letter-spacing-${kebab(path.split(".").slice(1).join("."))}: ${node.$value}px;`);
    else if (pxGroups.has(g)) lines.push(`--${g}-${kebab(path.split(".").slice(1).join("."))}: ${node.$value}px;`);
  }
  write("typography.css", block(":root", lines));
}

// ── 4. Product tokens → themes/<product>.css ─────────────────────────────────
const SEMANTIC_GROUPS = ["text", "link", "icon", "background", "border"];
for (const [product, file] of [
  ["tashilpay", "2. Product Tokens.TashilPay.json"],
  ["zamyad", "2. Product Tokens.Zamyad.json"],
  ["zhina", "2. Product Tokens.Zhina.json"],
]) {
  const doc = read(file);
  const flat = flatten(doc); // includes embedded references.* / alpha.* for resolution
  const lines = [];
  for (const group of SEMANTIC_GROUPS) {
    if (!doc[group]) continue;
    const groupFlat = flatten(doc[group], group);
    for (const [path, node] of Object.entries(groupFlat)) {
      if (node.$type !== "color") continue;
      const css = resolveColor(node.$value, flat);
      if (css == null) { warn(`${product}: unresolved ${path}`); continue; }
      lines.push(`--color-${kebab(path)}: ${css};`);
    }
  }
  write(`themes/${product}.css`, block(`[data-theme="${product}"]`, lines));
}

console.log(`[tokens] done${warnings ? ` (${warnings} warning(s))` : ""}`);
