// Icon compiler: raw Figma SVG exports (src/icons/svg/*.svg) → tree-shakeable
// React components (src/icons/<Name>.tsx) + a barrel (src/icons/index.ts).
//
// Normalization (so every icon meets the two hard requirements) is done HERE,
// programmatically — the source SVGs are never hand-edited:
//   • colorable  → strip hardcoded fills (black / hex / none) so paths inherit
//                  the <svg fill="currentColor">, i.e. the CSS `color` cascade.
//   • resizable  → drop the fixed width/height="24"; render at 1em (scales with
//                  font-size / the consumer's width). viewBox is preserved.
//   • JSX-safe   → kebab attributes (fill-rule, clip-rule, …) → camelCase.
//
// Generated files are git-ignored and regenerated by `pnpm icons`.
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SVG_DIR = join(repoRoot, "src", "icons", "svg");
const OUT_DIR = join(repoRoot, "src", "icons");

// filename (sans .svg) → PascalCase, namespaced with an `Icon` prefix so icon
// exports never collide with component exports or reserved words.
function componentName(file) {
  const base = file.replace(/\.svg$/i, "");
  const parts = base
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2") // split camelCase: interestRate → interest Rate
    .split(/[^a-zA-Z0-9]+/) // split on -, _, space: Square-1 → Square 1
    .filter(Boolean)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1));
  return "Icon" + parts.join("");
}

const GRID = 24; // canonical icon grid

// raw <svg>…</svg> text → normalized JSX component source.
function toComponent(svgText, name) {
  const rawViewBox = (svgText.match(/viewBox="([^"]+)"/) || [])[1] || `0 0 ${GRID} ${GRID}`;
  let inner = svgText
    .replace(/^[\s\S]*?<svg[^>]*>/i, "") // drop everything up to & incl. the <svg …> tag
    .replace(/<\/svg>\s*$/i, "") // drop the closing tag
    .trim()
    // strip hardcoded fills → inherit currentColor; keep `opacity` (duotone).
    .replace(/\s*fill="(?:black|none|#[0-9A-Fa-f]{3,8}|rgb[^"]*)"/g, "")
    // kebab-case attrs → camelCase for JSX (fill-rule, clip-rule, stroke-width, …)
    .replace(/([a-z]+)-([a-z]+)=/g, (_, a, b) => a + b.charAt(0).toUpperCase() + b.slice(1) + "=");

  // Normalize odd-grid icons (e.g. 20×20) onto the canonical 24×24 grid by
  // scaling their content, so every exported icon shares one coordinate system.
  let viewBox = rawViewBox;
  const [minX, minY, w, h] = rawViewBox.split(/\s+/).map(Number);
  if (minX === 0 && minY === 0 && (w !== GRID || h !== GRID) && w > 0 && h > 0) {
    const s = +(GRID / Math.max(w, h)).toFixed(6);
    console.warn(`[icons] ${name}: viewBox ${rawViewBox} → scaling ×${s} onto ${GRID}-grid`);
    inner = `<g transform="scale(${s})">\n${inner}\n</g>`;
    viewBox = `0 0 ${GRID} ${GRID}`;
  }
  inner = inner.replace(/\n\s*/g, "\n      ");
  return `import type { SVGProps } from "react";

export function ${name}(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      width="1em"
      height="1em"
      viewBox="${viewBox}"
      fill="currentColor"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      ${inner}
    </svg>
  );
}
`;
}

const files = readdirSync(SVG_DIR).filter((f) => f.toLowerCase().endsWith(".svg")).sort();
if (!files.length) {
  console.error(`[icons] no SVGs found in ${SVG_DIR}`);
  process.exit(1);
}

// Remove previously generated components for a clean rebuild. Only touch
// generated artifacts: the per-icon `Icon*.tsx` files and the barrel. Never the
// svg/ source or hand-written files like `*.stories.tsx`.
for (const f of readdirSync(OUT_DIR)) {
  if ((/^Icon.*\.tsx$/.test(f) && !f.endsWith(".stories.tsx")) || f === "index.ts") {
    rmSync(join(OUT_DIR, f));
  }
}
mkdirSync(OUT_DIR, { recursive: true });

const used = new Map(); // name → source file, to detect & resolve collisions
const exports = [];
for (const file of files) {
  let name = componentName(file);
  if (used.has(name)) {
    let i = 2;
    while (used.has(`${name}${i}`)) i++;
    console.warn(`[icons] name collision: ${file} & ${used.get(name)} → renaming to ${name}${i}`);
    name = `${name}${i}`;
  }
  used.set(name, file);
  const svg = readFileSync(join(SVG_DIR, file), "utf8");
  writeFileSync(join(OUT_DIR, `${name}.tsx`), toComponent(svg, name));
  exports.push(`export { ${name} } from "./${name}";`);
}

const banner = "// GENERATED by scripts/build-icons.mjs — do not edit.\n";
writeFileSync(join(OUT_DIR, "index.ts"), banner + exports.join("\n") + "\n");
console.log(`[icons] generated ${files.length} icon components → src/icons/`);
